### ISSUE TITLE
Connecting to CARLA on port 2002

### ISSUE THREAD

**Issue by Katikonst** [javyduck/ChatScene#10]
After the update with dynamic mode,ChatScene is trying to connect on port 2002,but we still have the port==2000 in the repo. Is there a specific reason?

**Comment by javyduck** [comment]
Sorry for the confusion, I used port 2002 on my server for testing, if it is 2000 on you case, you can just set the port with 
--port 2000 and --tm_port 8000
https://github.com/javyduck/ChatScene/blob/b60ec6ea723b5c6c44f5fd6ff1e3f1a0ac45d929/scripts/run_train_dynamic.py#L44
It depends on which port you are using for running Carla.

**Comment by Katikonst** [comment]
Appreciate the quick response!

**Comment by AHPUymhd** [comment]
> Sorry for the confusion, I used port 2002 on my server for testing, if it is 2000 on you case, you can just set the port with --port 2000 and --tm_port 8000
> 
> https://github.com/javyduck/ChatScene/blob/b60ec6ea723b5c6c44f5fd6ff1e3f1a0ac45d929/scripts/run_train_dynamic.py#L44
> 
> 
> It depends on which port you are using for running Carla.

Can the latest version of Carla run code, please？

**Comment by javyduck** [comment]
I doubt it can't, different version of CARLA will use different definition of some APIs, but you can feel free to have a try.
