### ISSUE TITLE
Vehicle spawned in carla

### ISSUE THREAD

**Issue by Katikonst** [javyduck/ChatScene#13]
Hello! I would like to ask if it is possible to get the vehicle_id of a vehicle that is used in chatscene and put my own sensors on it to retrieve data.

**Comment by javyduck** [comment]
hi, by default, we already recorded the data for the surrounding vehicles in the saved pkl, you can check and modify here to do the update:
https://github.com/javyduck/ChatScene/blob/db2f348df1ccf3a96f8841dde75db8c59ee63c87/safebench/scenario/scenario_definition/scenic_scenario.py#L125
 so you can feel free to put your own sensor on it to retrieve the data you want. : )

**Comment by Katikonst** [comment]
thank you very much!

**Comment by Katikonst** [comment]
> hi, by default, we already recorded the data for the surrounding vehicles in the saved pkl, you can check and modify here to do the update:
> 
> https://github.com/javyduck/ChatScene/blob/db2f348df1ccf3a96f8841dde75db8c59ee63c87/safebench/scenario/scenario_definition/scenic_scenario.py#L125
> 
> 
> so you can feel free to put your own sensor on it to retrieve the data you want. : )



> hi, by default, we already recorded the data for the surrounding vehicles in the saved pkl, you can check and modify here to do the update:
> 
> https://github.com/javyduck/ChatScene/blob/db2f348df1ccf3a96f8841dde75db8c59ee63c87/safebench/scenario/scenario_definition/scenic_scenario.py#L125
> 
> 
> so you can feel free to put your own sensor on it to retrieve the data you want. : )



> hi, by default, we already recorded the data for the surrounding vehicles in the saved pkl, you can check and modify here to do the update:
> 
> https://github.com/javyduck/ChatScene/blob/db2f348df1ccf3a96f8841dde75db8c59ee63c87/safebench/scenario/scenario_definition/scenic_scenario.py#L125
> 
> 
> so you can feel free to put your own sensor on it to retrieve the data you want. : )

Could you please enlighten me where can i get the id from the ego_vehicle?I want to print all the actors_id from each scene.Thank you!

**Comment by Katikonst** [comment]
thank you!
