### ISSUE TITLE
Carla 0.9.12

### ISSUE THREAD

**Issue by Yxj-study** [javyduck/ChatScene#17]
Can I use CARLA 0.9.12 instead of 0.9.13?

**Comment by javyduck** [comment]
i think it should be fine... you can have a try first, and we have also provided the link of carla 0.9.13 for you to download.

**Comment by Yxj-study** [comment]
Step 6: Run sudo apt install libomp5 as per this https://github.com/carla-simulator/carla/issues/4498.

If I am using a Windows system, can I skip this step?

**Comment by Yxj-study** [comment]
> i think it should be fine... you can have a try first, and we have also provided the link of carla 0.9.13 for you to download.

Hello, I created a virtual machine on VMware with Ubuntu, but it's running very slowly and downloading software is also very slow. Do you have any good suggestions?

**Comment by javyduck** [comment]
Hi, for downloading software => do you mean downloading the carla? or downloading the packages required for running the code.

**Comment by Yxj-study** [comment]
> Hi, for downloading software => do you mean downloading the carla? or downloading the packages required for running the code.

Anaconda， Carla and so on

**Comment by javyduck** [comment]
it's normal generally, maybe you can use screen to download it over the night...

**Comment by Yxj-study** [comment]
> it's normal generally, maybe you can use screen to download it over the night...

I installed Ubuntu as a dual boot, and the problem has improved. However, I can access GitHub but cannot use ChatGPT. When I open the ChatGPT website, it remains unresponsive. What should I do？

**Comment by javyduck** [comment]
I will try to provide a new version and fine-tune an open-sourced LLM for this repository in the upcoming months (if i am not quite busy)... maybe you can test that, currently, i would prefer to use the static version, or the dynamic version without GPT first (I will update the new database to be compliable with the 50 cases in static version for at most two weeks).

**Comment by Yxj-study** [comment]
> I will try to provide a new version and fine-tune an open-sourced LLM for this repository in the upcoming months (if i am not quite busy)... maybe you can test that, currently, i would prefer to use the static version, or the dynamic version without GPT first (I will update the new database to be compliable with the 50 cases in static version for at most two weeks).

Okay, I will keep an eye on your projects. During this time, I will first familiarize myself with how to use it.

**Comment by hulaideyoushou** [comment]
so are you failed in the "Windows system+CARLA_0.9.12"? I also want to try this combination……
