### ISSUE TITLE
I wonder if the code will be open source soon?

### ISSUE THREAD

**Issue by lili124** [javyduck/ChatScene#2]
Your research is very meaningful! When will the author consider uploading the code to the repository?

**Comment by jayyoung0802** [comment]
+1

**Comment by javyduck** [comment]
Hi,

Thank you for your interest. I apologize for the delay; it indeed took some time to clean up the code...

I have now committed the main version that replicates the primary results shown in our paper, specifically for fixed routes and scenarios. Currently, I am focusing on cleaning the dynamic mode, which involves integrating our retrieval database with GPT-4o. This integration aims to enhance the diversity of the Scenic code generated for _any text-described scenario_. We aim to complete this component within one week.

Thank you again for your interest! If you encounter any issues while running our code, please don't hesitate to let me know.

**Comment by lili124** [comment]
Thank you for releasing this very interesting project!
