### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by Yxj-study** [javyduck/ChatScene#25]
File "retrieve.py", line 161, in <module>
    current_adv_object, current_behavior, current_geometry, current_spawn = [s.strip() for s in match.groups()]
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by zhatlaen** [comment]
hello, how do you resolve this error?

**Comment by Yxj-study** [comment]
I do not solve this problem，sometimes it can work.



---Original---
From: ***@***.***&gt;
Date: Wed, Nov 20, 2024 21:50 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [javyduck/ChatScene] AttributeError: 'NoneType' object has noattribute 'groups' (Issue #25)




 
hello, how do you resolve this error?

**Comment by Yxj-study** [comment]
OK，thanks for your help, please send a letter to me when you solve the problem.



---Original---
From: "Jiawei ***@***.***&gt;
Date: Tue, Dec 10, 2024 14:22 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [javyduck/ChatScene] AttributeError: 'NoneType' object has noattribute 'groups' (Issue #25)




 
hi, i see the problem, i will try to solve it this week
