### ISSUE TITLE
dynamic model--No pedestrians

### ISSUE THREAD

**Issue by Yxj-study** [javyduck/ChatScene#32]
I followed the instructions on your GitHub, but I found that there are no pedestrians.So I tried changing the contents of the scenario_descriptions.txt file. The content is as follows:

The ego vehicle is driving straight on a two-lane road when another vehicle suddenly appears from the opposite direction in the same lane and moves towards the ego vehicle. The two vehicles collide head-on in the middle of the road.
The ego vehicle is driving straight through a four-way intersection when a second vehicle suddenly runs a red light from the perpendicular road and enters the intersection, causing a T-bone collision with the ego vehicle.
The ego vehicle is traveling along a highway when another vehicle unexpectedly swerves into the ego vehicle's lane while trying to overtake another car, resulting in a side-impact collision.
The ego vehicle is driving through a roundabout when another vehicle entering from the opposite direction fails to yield and crashes into the ego vehicle’s side as it exits the roundabout.
The ego vehicle is driving straight on a rural road when a second vehicle suddenly appears in the ego vehicle’s lane after taking a blind curve, causing a head-on collision.

I ran retrieve.py, and then a Scenic file was generated in the dynamic_scenario folder. The content of the file is as follows:
'''The ego vehicle is driving straight on a two-lane road when another vehicle suddenly appears from the opposite direction in the same lane and moves towards the ego vehicle. The two vehicles collide head-on in the middle of the road.'''
Town = 'Town01'
param map = localPath(f'../maps/{Town}.xodr') 
param carla_map = Town
model scenic.simulators.carla.model
EGO_MODEL = "vehicle.lincoln.mkz_2017"

behavior AdvBehavior():
    while (distance to self) > 60:
        wait  # The adversarial vehicle maintains its course until it closes in on a specified proximity.
    do FollowLaneBehavior(target_speed=globalParameters.OPT_ADV_SPEED) until (distance to self) < globalParameters.OPT_ADV_DISTANCE
    # Once within a certain distance, the adversarial vehicle executes a lane change.
    do LaneChangeBehavior(laneSectionToSwitch=network.laneSectionAt(ego), target_speed=globalParameters.OPT_ADV_SPEED)

param OPT_ADV_SPEED = Range(0, 20)  # Controls the speed of the adversarial vehicle.
param OPT_ADV_DISTANCE = Range(10, 30)  # The distance at which the adversarial vehicle starts its lane change maneuver.
# Collecting lane sections that have a left lane (opposite traffic direction) and no right lane (single forward road)
laneSecsWithLeftLane = []
for lane in network.lanes:
    for laneSec in lane.sections:
        if laneSec._laneToLeft is not None and laneSec._laneToRight is None:
            if laneSec._laneToLeft.isForward != laneSec.isForward:
                laneSecsWithLeftLane.append(laneSec)

# Selecting a random lane section that matches the criteria
EgoLaneSec = Uniform(*laneSecsWithLeftLane)
EgoSpawnPt = OrientedPoint in EgoLaneSec.centerline
# Parameters for scenario elements
param OPT_GEO_BLOCKER_Y_DISTANCE = Range(0, 40)
param OPT_GEO_X_DISTANCE = Range(-8, 0)  # Offset for the agent in the opposite lane
param OPT_GEO_Y_DISTANCE = Range(10, 30)

# Setting up the parked car that blocks the ego's path
laneSec = EgoLaneSec  # Assuming EgoLaneSec is predefined in the geometry part
IntSpawnPt = OrientedPoint following roadDirection from EgoSpawnPt for globalParameters.OPT_GEO_BLOCKER_Y_DISTANCE
Blocker = Car at IntSpawnPt,
    with heading IntSpawnPt.heading,
    with regionContainedIn None

# Setup for the motorcyclist who unexpectedly enters the scene
SHIFT = globalParameters.OPT_GEO_X_DISTANCE @ globalParameters.OPT_GEO_Y_DISTANCE
AdvAgent = Car at Blocker offset along IntSpawnPt.heading by SHIFT,
    with heading IntSpawnPt.heading + 180 deg,  # The agent is facing the opposite direction, indicating oncoming
    with regionContainedIn laneSec._laneToLeft,  # Positioned in the left lane, assuming it's the oncoming traffic lane
    with behavior AdvBehavior()

But my command line is showing the following error:
![91b37082-ba33-43e8-9d74-5ee4e7ac9009](https://github.com/user-attachments/assets/16aad407-b012-4559-ac99-266dd2264d03)

If I want to generate a vehicle collision scenario and run it jointly with Carla, what should I do?

**Comment by silakuzu** [comment]
Hello, I get a similar error. Could you let me know how you solved it? @Yxj-study

**Comment by Yxj-study** [comment]
@silakuzu    I tried the case again. I tried the example again, and then I saw these little dots on the map representing pedestrians, which I didn't find on Carla. 
![image](https://github.com/user-attachments/assets/387d4172-44db-4381-8ba4-38ecd22ae5f3)
