### ISSUE TITLE
Conflicting Dependencies

### ISSUE THREAD

**Issue by Katikonst** [javyduck/ChatScene#7]
hello,I have issues with installing ChatScene.More specifically,I get an error about moviepy==1.0.3(it needs decorator<5.0),but scenic 2.1.0b4 needs decorator~=5.0. How can I solve this?

**Comment by javyduck** [comment]
hi, you can try to install decorator with version 5.1.1, it works in my side.

**Comment by Katikonst** [comment]
thank you very much,it worked fine!
